version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jasur1803
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network


  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - ecommerce-network

  app:
    build: .
    container_name: spring-app
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ecommerce_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=jasur1803

      # Redis sozlamalari (Ilova Redisga ulanishi uchun)
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

      # FLYWAY SOZLAMALARI (Shu yerda yoqiladi va log yoziladi)
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true

      # LOGLARNI SOZLASH (Konsolda baza va Flyway jarayonini batafsil ko'rish uchun)
      - LOGGING_LEVEL_ORG_FLYWAYDB=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    restart: on-failure


volumes:
  pg_data:


networks:
  ecommerce-network:
    driver: bridge
